import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "../components/nav/nav";
import Translate from "../components/translate/Translate";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Das Forum",
  description: "Generated by create next app",
};

function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav />
        <main>{children}</main>
        <Translate />
      </body>
    </html>
  );
}

export default RootLayout;
